server:
  port: 8080
  servlet:
    context-path: /
spring:
  application.name: employee-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  pid.file: ${java.io.tmpdir}/employee-service-api.pid
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: employee-service-dbconnectionpool
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: validate
  kafka:
    consumer:
      group-id: myway
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.myway.dto
---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5419/employee_event
    username: postgres
    password: employee_event
server:
  port: 8019
springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8019
---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db
  flyway:
    enabled: false
  jpa:
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create
logging:
  level:
    root: error
